backend:
  name: git-gateway

media_folder: "/dist/uploads"
public_folder: "/uploads"

collections:
  - name: "featuredproducts"
    label: "Featured Products"
    folder: "src/featured"
    slug: "{{title}}"
    create: true
    fields:
      - name: title
        label: Title (optional)
        widget: string
      - { label: "tags", name: "tags", widget: "string", default: "featured" }
      - name: headline
        label: Headline (optional)
        widget: string
      - name: subtitle
        label: Sub Headline (optional)
        widget: string
      - name: soldout
        label: Sold Out
        widget: boolean
      - { label: 'Cover Image', name: 'coverimage', widget: 'image' }
      - name: buttonText
        label: Button Text
        widget: string
      - {
          label: 'Button Style',
          name: 'buttonStyle',
          widget: 'select',
          options: ['primary', 'outline', 'accent'],
          multiple: false,
        }
      - name: linkTo
        label: Button Link
        widget: string